[project]
name = "foxglove-sdk-demo"
version = "0.1.0"
description = "Experimenting with the Foxglove SDK"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["foxglove-sdk>=0.7.1", "numpy>=1.26.0"]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.8",
    "watchfiles>=1.0.5",
]

[tool.ruff.lint]
# Enable pycodestyle (E), Pyflakes (F), and isort (I) rules for linting.
# E: Style errors and warnings from pycodestyle
# F: Logical/syntax errors detected by Pyflakes
# I: Import sorting and formatting rules from isort
select = ["E", "F", "I"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
known-first-party = ["sdk-game"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "numpy.*"
ignore_missing_imports = true
